include::_attributes.adoc[]

[[quick-reference-guide]]
== Quick Reference Guide

The quickest way to create validations using Espilce Periksa is to create a class containing static methods that are annotated with the `@Check` annotation.
The first argument of the method is the model element to validate and the second argument injects the validation context as provided by Espilce Periksa.
For more information, please read the <<programmers-guide>>. +
The example below adds a duplicate value error-validation for command names to the Fowler state-machine DSL Xtext example, and an info-validation for state names to start with a capital.

NOTE: Using the `@Check` annotation requires a bundle dependency of `org.espilce.periksa.validation`.

.Writing validations using Espilce Periksa
[source,java]
----
package validations; 

public class StatemachineValidations {
	@Check // <1>
	public static void checkDuplicates(Statemachine statemachine, CheckContext context) {
		ValidationLibrary.checkDuplicateValue(statemachine.getCommands(), StatemachinePackage.Literals.COMMAND__NAME, context); // <2>
	}

	@Check
	public static void checkNameStartsWithCapital(State state, CheckContext context) {
		if (!state.getName().isEmpty() && state.getName().charAt(0) != Character.toUpperCase(state.getName().charAt(0))) {
			context.getReport().info("Name should start with upper case", StatemachinePackage.Literals.STATE__NAME); // <3>
		}
	}
}
----

<1> The `@Check` annotation registers the method to validate all instances of `Statemachine` as per the first argument of the method. The method is invoked for each `statemachine` instance in the model.
<2> Espilce Periksa provides a `ValidationLibrary` containing reusable validations, e.g. validating duplicates in feature values.
<3> The API of Espilce Periksa allows to easily report an `info`, `warning` or `error`.

Then you need to register your model validations, such that they will be automatically invoked as part of validating each applicable model instance.
The easiest way to do this is by means of an extension point that is provided by Espilce Periksa, as per the example below.

.Registering validations in plugin.xml
[source,xml]
----
<plugin>
   <extension
         point="org.espilce.periksa.validation.registry.registrar">
      <ReflectiveValidator
            class="validations.StatemachineValidations">
         <EPackage
               uri="http://www.eclipse.org/xtext/example/fowlerdsl/Statemachine">
         </EPackage>
      </ReflectiveValidator>
   </extension>
</plugin>
----
